### ISSUE TITLE
Error when evaluating puzzle accuracy

### ISSUE THREAD

**Issue by noiper** [google-deepmind/searchless_chess#3]
I am trying to evaluate the puzzle accuracy on my locally trained model, and got this error: 
(In training_utils.py Line 283)
step =checkpoint steps[-1]
IndexError: list index out of range
Does anyone know how to fix it?

**Comment by anianruoss** [comment]
Hi Robin, the error states that there are no checkpoints, which means that you either didn’t save any checkpoints or you’re trying to load them from the wrong directory.
